### ISSUE TITLE
Externalized configuration

### ISSUE THREAD

**Issue by bitmarte** [totaljs/dashboard#1]
Hi @petersirka ,
first of all congrats for your great job!

I would expose to you two possible features
1. could you externalize config files with a custom arg, like port done? I would like to change some configurations wihout changes on your code, just using your dashboard app as npm dependency.
2. I would like to externalize also the "/databases" folder

What is your opinion about it?
Thanks a lot,
M.

**Comment by petersirka** [comment]
Hi @bitmarte, a lot of thank you. It's too complicated to answer but `dashboard` is created for its modifications. So don't worry and modify the code by your needs. Currently I want to create some widgets (but I don't have any time for it yet, e.g.: <https://dashboard.totaljs.com/iot/battery.html>).

---

So my opinion is: modify it per your needs.

**Comment by bitmarte** [comment]
Hi @petersirka , thank you for your quick answer.
So, I will fork your repo and I will check your updates in the future with a compare and merge job.

M.
