### ISSUE TITLE
dashboard v7 not working..

### ISSUE THREAD

**Issue by KangGeunSu** [totaljs/dashboard#10]
Hello

It doesn't work since v7.

![image](https://user-images.githubusercontent.com/11586458/73799855-77787300-47fa-11ea-8c6c-f63d18a7b60f.png)

"APPLY SETTIGNS" is not activated even if "Flow instance" is selected

My PC info
```
Node.js       : v8.17.0
Total.js      : v3.3.0
OS            : linux 4.15.0-76-generic
Memory        : 12.36 MB / 21.66 MB
User          : kgs
```

v6 works fine. OTL..

**Comment by petersirka** [comment]
I'll look into it today.

**Comment by molda** [comment]
Hi, i fixed some components already. Just update them.
https://github.com/totaljs/dashboardcomponents/commit/02b580f3dc85961e74390ba674acc27675ea4755

**Comment by petersirka** [comment]
I have updated CDN.

**Comment by KangGeunSu** [comment]
OK! This is solved.
Thank you!

One more

![image](https://user-images.githubusercontent.com/11586458/73932836-7b051a80-491e-11ea-9cfd-7c746622254c.png)

The checkbox doesn't work.

Thank You

**Comment by KangGeunSu** [comment]
![image](https://user-images.githubusercontent.com/11586458/73994710-cdcfe800-4999-11ea-80c1-42e9db97edff.png)
 This Error

**Comment by molda** [comment]
I'll have a look at the checkbox over the weekend.

When does the error pops up?

**Comment by KangGeunSu** [comment]
Sorry for late reply

Error when downloading component.

For example, if you try to download only device_light, you get an error

Thank you

**Comment by molda** [comment]
I have found the problem with the checkboxes but i didn't have time over the weekend.
I'll try to fix it today.

For now if you want to use Dashboard just copy *.html files from https://github.com/totaljs/dashboardcomponents to <app>/dashboard/ so you get for example <app>/dashboard/device_light.html

**Comment by petersirka** [comment]
I have fixed it. Please download latest version of Dashboard from GitHub and let me know.

**Comment by KangGeunSu** [comment]
Thank you for your concern

The title is v6.

Thank you!

**Comment by petersirka** [comment]
I have looked into the source-code and the problem with title has been fixed. Dashboard has open one more issue and Martin solves it. I'll wait for a solution and I'll make a release.

Thx.
