### ISSUE TITLE
Redirect HTTP to HTTPS

### ISSUE THREAD

**Issue by hepr** [totaljs/dashboard#2]
Hi Peter,

what do you think about nginx 302 redirect automatic on HTTP when a HTTPS server was configured ?

When using HTTPS server, we can add a checkbox in admin interface to create automatic redirect to https.

Is it a good solution ?

Thanks

Herve

**Comment by petersirka** [comment]
Hi @hepr, did you mean __SuperAdmin__ not __Dashboard__, right? :-)

**Comment by hepr** [comment]
Yes sorry Peter
It's on superadmin :-)

Envoyé de mon iPhone

**Comment by petersirka** [comment]
A new version of __SuperAdmin__ supports this feature <https://github.com/totaljs/superadmin/tree/v5.0.0>

👍
