### ISSUE TITLE
New login missing controller.cookie function

### ISSUE THREAD

**Issue by swilleyman** [totaljs/dashboard#3]
Just testing out some of the new work and it looks like a piece is missing from the controller.

The login is calling controller.cookie which does not appear to exist.  

[TypeError: controller.cookie is not a function]
======= 2016-12-29 11:06:53: TypeError: controller.cookie is not a function TypeError: controller.cookie is not a function
    at DatabaseBuilder.$callback (/home/xxxxxxx/totaljs/dashboard/models/user.js:17:17)
    at /usr/lib/node_modules/total.js/nosql.js:560:13
    at Immediate.<anonymous> (/usr/lib/node_modules/total.js/index.js:380:5)
    at Immediate.immediate._onImmediate (timers.js:440:18)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by petersirka** [comment]
Hi @swilleyman, I messed up the repository, but try to download branch <https://github.com/totaljs/dashboard/tree/v3.0.0>. I perform big changes and improvements, so I'll publish it early next year. I have to add user management and create better demo of dashboard.

PS: which version of Total.js do you use? Try to download latest version.

Sorry and thank you!

**Comment by swilleyman** [comment]
I was still using v2.2.0.  I upgraded to 2.3.0.  Things appear to be working now.  Thanks!  

Great work on the framework, bye the way.

**Comment by petersirka** [comment]
Thank you!
